---
title: "Project Proposal"
author: "Xinwei Han (xh2601), Xinhui Lin (xl3054), Ruohan Lyu (rl3610), Xinyin Miao (xm2356), Fenglin Xie (fx2212)"
date: "2025-11-07"
output: github_document
---

**Project Title:**

Tiny Paws, Big Rescue: A Data Story of Seasonal and Spatial Animal Saving

**The motivation for this project**: Animals play an essential role in maintaining ecological balance, yet those living in NYC face unique challenges. By analyzing Urban Park Ranger Animal Response dataset, we aim to identify when and where animals need the most help, ultimately raising public awareness and supporting timely rescue and conservation efforts.

**The intended final products**: The goal of our project is to develop an interactive, data-driven website that allows visitors to explore the animal rescue data through various visualizations. Interactive maps will be the centerpiece of our website, visualizing the distribution of animals encountered by Park Rangers. The animal distribution map will display the geographical locations of animal aid incidents, allowing users to filter by animal species and seasons to identify "hot spots" for specific types of animals or high-risk areas.

**The anticipated data sources**: Our primary dataset is provided by the Department of Parks and Recreation (DPR) and is made publicly available through the NYC OpenData portal [(Urban Park Ranger Animal Condition Response)](https://data.cityofnewyork.us/Environment/Urban-Park-Ranger-Animal-Condition-Response/fuhs-xmg2/about_data). This dataset contains 6,385 records of animal rescue requests, including detailed information such as the date and time of each call, ranger response time, park name, specific location descriptions, animal species, and the condition of the animals involved.

**The planned analyses / visualizations / coding challenges**: We plan to analyze the associations between animal conditions, locations, and time, both across the year and throughout the day. Additional analyses will examine factors that may influence response time, such as park location, animal condition or number, and temporal variables like time of day or frequency within a week or month. Examples of visualizations include a heatmap illustrating the density of injured animals by month and time of day, as well as violin plots grouped by boroughs to show the distribution of response times across regions. We will also conduct statistical tests, such as ANOVA, to evaluate relationships among variables, including borough, response time, animal condition, and time factors.

Some challenges include the absence of geographic coordinates for parks and the lack of standardization in detailed location descriptions (e.g., “West 97th St entrance,” “Garbage can”). To create accurate map visualizations, we will match each park with its corresponding geographic coordinates. In addition, we plan to apply natural language processing (NLP) techniques to identify and understand patterns in the location information, improving the consistency and interpretability of spatial analyses.

**Project Timeline**

October 31- November 7: brainstorm project ideas, confirm dataset, finalize analysis plans

November 8-15: clean and integrate data (with geocoded location), revise hypotheses and methods based on feedback, begin preliminary analysis

November 16-23: conduct exploratory analysis and generate visualizations

November 24-30: draft written report and begin building project website

December 1-6: finalize report, webpage, screencast, and peer assessment for submission
